### ISSUE TITLE
Why do you have composer.lock in this repository

### ISSUE THREAD

**Issue by robinlehrmann** [patchlevel/event-sourcing#142]
Hi @DanielBadura and @DavidBadura as far as I know the composer.lock shouldn't be in a library so I guess it should be removed no?

Or is there a specific reason for that the `composer.lock` exists in the project ?

**Comment by DanielBadura** [comment]
Yes there is a reason: the static code analyser etc.
With this we can ensure the right versions gets installed and dont need to fallback to `.phar` solutions or something else.

But the userland dont get the `composer.lock` shipped since it's ignored for the export. See here: https://github.com/patchlevel/event-sourcing/blob/1.1.x/.gitattributes#L6
