### ISSUE TITLE
Google Protocol Buffers

### ISSUE THREAD

**Issue by robinlehrmann** [patchlevel/event-sourcing#310]
Hi :)

I'm currently playing a bit with [Google Protocol Buffers](https://developers.google.com/protocol-buffers).

Do you have an idea how this can be integrated?

My problem is the generated code of probuf... It generates setters and getters for the events but I want to extend from the generated classes, because a change of the events will update the files in every file automatically and would break the events payload.

I know this is not directly related to your lib but maybe you have an idea regarding this :)

**Comment by DanielBadura** [comment]
I never worked with that before. I just quickly read over some docs and the php implementation repo docs. It seems it is a file format like xml or json is. So I would think we would need to offer support for other encoders then JSON. But I'm not sure since I only quickly read the docs. 

What confuses me is the part you wrote about the getter setter generation on the events. Can you share some more details how you right now tried to use it together?

**Comment by DavidBadura** [comment]
In the end, the library doesn't care how the events look like and where they come from. If you want to generate events dependent on proto files then you can do it. The only thing you then have to make sure is that the whole thing is serializable into a string.

The extension point would then be here: https://github.com/patchlevel/event-sourcing/blob/2.1.x/src/Serializer/EventSerializer.php

**Comment by robinlehrmann** [comment]
@DanielBadura I've generated only some event classes and was thinking about how to map them to my existing events 🤔 but @DavidBadura already answered the question. :)
