### ISSUE TITLE
Time-travel debugging

### ISSUE THREAD

**Issue by signor-pedro** [patchlevel/event-sourcing#619]
Hello, first of all, thank you for this fantastic library. ❤️ 

In our company, we are trying to migrate v2 to v3.

However, we are completely baffled by how to do a simple time-travel debug.

We have a `Wallet` aggregate and a common support team's use case is: "Determine how much money was in the wallet at a given time, e.g. yesterday at 14:34:12."

Perhaps we are misunderstanding something, but is that not the killer feature of ES and should it not be possible in a simple manner?

We tried to use different kinds of subscriptions and ended up implementing a "hacky" solution when, before each command run, we reset the playhead of the subscription.

Thank you for telling us (and ideally documenting) how to do this properly.

**Comment by naril** [comment]
Hi, I'm from same company and I will only add that our biggest problem is that subscription, even if it's defined as "from beginning" runs from beginning only once. With next execution it runs from last position. We need it to run from beginning every time. In version 2 we used for that Pipeline with custom target.

**Comment by DavidBadura** [comment]
Hey, I'm glad you like the library.

I'm not 100% sure if I understand the use case correctly. But I can try to share some information and possibilities.

Yes, the greatest strength of event sourcing is that all events are in the database and you can delete projections at any time and rebuild them.

But that doesn't necessarily have to happen via the subscription engine. The subscription engine is basically a daemon that is there to permanently manage subscriptions or to carry out a (globally) migration. It's perfect for (non-dynamic) projections, sending emails, etc.

Your use case is a little different. I think you want to know the status of one wallet (aggregate) and not view all wallets to the status x days ago, right?

You can easily access the event store yourself, use Message Translator and either save it in a DB or even display it in real time (which would be my preferred method).

We are experimenting with a dashboard for event sourcing and we have also built in a time travel feature for debugging, which happens in run-time.

https://github.com/patchlevel/event-sourcing-admin-bundle/blob/1.0.x/src/Controller/InspectionController.php#L140

If you want to stay with the subscription engine because you want to jump to the point in time globally, then you should not manipulate the position but delete the subscription using the remove method. This will rebuild the subscription/projection.

I hope I was able to help, otherwise just keep asking :)

**Comment by DavidBadura** [comment]
And if you want to stick with the pipeline principle, you can build the following class:

```php
<?php

declare(strict_types=1);

namespace App;

use Closure;
use Patchlevel\EventSourcing\Message\Translator\ChainTranslator;
use Patchlevel\EventSourcing\Message\Translator\Translator;
use Patchlevel\EventSourcing\Message\Translator\UntilEventTranslator;
use Patchlevel\EventSourcing\Store\Store;

final class Pipeline
{
    private ChainTranslator $translator;

    /** @param list<Translator> $translators */
    public function __construct(private Store $store, private MyTarget $target, array $translators = [])
    {
        $this->translator = new ChainTranslator($translators);
    }

    public function run(Closure|null $observer = null): void
    {
        foreach ($this->store->load() as $message) {
            $result = ($this->translator)($message);

            foreach ($result as $resultMessage) {
                $this->target->save($resultMessage);
            }

            if (!$observer) {
                continue;
            }

            $observer($message);
        }
    }

    public function count(): int
    {
        return $this->store->count();
    }
}
```

And you can use it as usual:

```php
$pipeline = new Pipeline($store, $myTarget, [new UntilEventTranslator(new \DateTimeImmutable('2021-01-01'))]);
$pipeline->run();
```

So, in the end my tip is: use the store directly, you can use Translator to customize the stream/messages and you can do whatever you want with it.

**Comment by signor-pedro** [comment]
Hi, thank you for the detailed explanation 👍 

Now that you explain it, indeed we might have been misusing even the v2 pipelines.

The example you provide in the Controller is simple and makes sense, we will be using this approach.

Thanks!
